//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by res.rc
//
#define IDR_MENUBOT                     101
#define IDB_BITMAP1                     106
#define IDI_ICON1                       107
#define IDD_CONFIG                      109
#define IDD_PROFILE                     110
#define IDB_BITMAP3                     119
#define IDD_BOTS                        122
#define IDD_ABOUT                       123
#define IDD_CREATECLAN                  125
#define IDC_TAB1                        1000
#define CONFIG_CMDOK                    1006
#define CONFIG_CMDCANCEL                1007
#define CONFIG_TXTPERPACKET             1012
#define CONFIG_TXTIDLE                  1013
#define CONFIG_LSTPROFILES              1014
#define CONFIG_CBOFONT                  1017
#define CONFIG_CBOPLATFORM              1018
#define CONFIG_CBOCLIENT                1019
#define CONFIG_TXTNUMFILTER             1021
#define CONFIG_TXTKEYINUSEMSG           1022
#define CONFIG_TXTCDKEYOWNER            1022
#define PROFILE_CMDOK                   1023
#define PROFILE_CMDCANCEL               1024
#define PROFILE_TXTSEX                  1025
#define PROFILE_TXTLOCATION             1026
#define PROFILE_TXTDESCRIPTION          1027
#define PROFILE_LBLUSERNAME             1028
#define CONFIG_CBOBNLSSERVER            1038
#define CONFIG_PINGNEG1                 1039
#define CONFIG_PING0                    1040
#define CONFIG_PINGNORMAL               1041
#define CONFIG_PINGCUSTOM               1042
#define CONFIG_TXTVERBYTEWAR3           1043
#define CONFIG_CHKSHOWVOID              1044
#define CONFIG_TXTPERBYTE               1045
#define CONFIG_TXTVERBYTESTAR           1046
#define CONFIG_TXTVERBYTED2DV           1047
#define CONFIG_TXTVERBYTEW2BN           1048
#define CONFIG_CHKSHOWINFO              1049
#define CONFIG_CHKJOINPUBCHAN           1050
#define CONFIG_TXTEMAIL1                1051
#define CONFIG_CHKURLDETECT             1052
#define CONFIG_TXTEMAIL2                1053
#define CONFIG_CHKLOGCHAT               1054
#define CONFIG_LBLFONT                  1055
#define CONFIG_CMDNEWPROFILE            1056
#define CONFIG_CHKUSEANTIFLOOD          1057
#define CONFIG_CHKUSEFLOODPROTECT       1058
#define CONFIG_CHKFILTERNUMS            1059
#define CONFIG_CMDDELETEPROFILE         1060
#define CONFIG_CHKUSELVIMG              1061
#define CONFIG_CMDLOADPROFILE           1063
#define CONFIG_CMDUNLOADPROFILE         1064
#define CONFIG_CMDOPENPROFILEDIR        1065
#define CONFIG_LSTTOLOAD                1071
#define CONFIG_LSTOTHERPROFILES         1072
#define CONFIG_TXTUSER                  1073
#define CONFIG_TXTPASS                  1074
#define CONFIG_TXTHOME                  1075
#define CONFIG_CBOSERVER                1076
#define CONFIG_CBOCDKEY                 1077
#define CONFIG_TXTEXPKEY                1078
#define CONFIG_CRLOCALHASHING           1079
#define CONFIG_CREXTERNALHASHING        1080
#define CONFIG_CRBNLS                   1081
#define CONFIG_CRSKIP                   1082
#define CONFIG_TXTPINGCUSTOMVAL         1083
#define CONFIG_CHKPLUG                  1084
#define CONFIG_CHKFORCECREATE           1085
#define CONFIG_CHKCHANGEPASS            1086
#define CONFIG_TXTNEWPASS               1087
#define CONFIG_CHKAUTOREG               1088
#define CONFIG_CHKREGBACK               1089
#define CONFIG_TXTCOUNTRYNAME           1090
#define CONFIG_TXTCOUNTRYABBRIV         1091
#define CONFIG_CHKPROXY                 1092
#define CONFIG_CBOPROXY                 1093
#define CONFIG_TXTFONTSIZE              1094
#define CONFIG_CHKMERGELVRTB            1095
#define CONFIG_CHKTABATBOTTOM           1096
#define CONFIG_CHKGRADIENT              1096
#define CONFIG_CHKWARNEXIT              1097
#define CONFIG_CHKWARNPROFILE           1098
#define CONFIG_CHKTEXTPING              1099
#define CONFIG_CHKMAXIMIZEMDI           1100
#define CONFIG_CHKUSEATMOS              1100
#define CONFIG_CHKCLEARRTB              1101
#define CONFIG_TXTMAXRTBLEN             1102
#define CONFIG_TXTCHARSTOCLEAR          1103
#define CONFIG_CHKUSERTBIMG             1104
#define CONFIG_CHKUSEJOINGREET          1107
#define CONFIG_CHKUSELEAVEGREET         1108
#define CONFIG_TXTJOINGREET             1109
#define CONFIG_TXTLEAVEGREET            1110
#define CONFIG_TXTIDLEINTERVAL          1111
#define CONFIG_CMDSELECTHASHPATH        1118
#define CONFIG_CBOCLIENTS2              1119
#define BOTS_LVWDISPLAY                 1121
#define BOTS_CMDOK                      1122
#define CONFIG_CMDTOLOADSTARTUP         1123
#define CONFIG_CMDTONOTLOADSTARTUP      1124
#define CONFIG_TXTNEWPROFILE            1125
#define CONFIG_CMDOPENPROFILEINI        1126
#define ABOUT_OK                        1127
#define CONFIG_CHKFORMATLOGS            1128
#define CONFIG_CBOTABPOS                1130
#define CONFIG_LBLCLR1                  1132
#define CONFIG_LBLCLR2                  1133
#define IDC_CHECK1                      1143
#define IDC_CHECK2                      1144
#define IDC_EDIT1                       1145
#define IDC_RADIO1                      1147
#define IDC_RADIO2                      1148
#define IDC_RADIO3                      1149
#define IDC_CHECK4                      1150
#define IDC_EDIT2                       1151
#define IDC_EDIT3                       1152
#define CLAN_LVWCANDIDATES              1155
#define CLAN_CMDCHECK                   1156
#define CLAN_CMDCREATE                  1157
#define CLAN_CMDCANCEL                  1158
#define CLAN_TXTNAME                    1159
#define CLAN_TXTTAG                     1160
#define CLAN_LBLSTATUS                  1161
#define CONFIG_TXTRCRATE                1162
#define CONFIG_TXTXRCHANNEL             1163
#define CONFIG_TXTXRFACTOR              1164
#define CONFIG_CHKDECODE                1165
#define CONFIG_SLDGLASS                 1166
#define CONFIG_CHKUSEGLASS              1167
#define CONFIG_CMDRTBSELIMG             1400
#define CONFIG_CMDLVSELIMG              1401
#define CONFIG_OPTIDLENONE              1500
#define CONFIG_OPTIDLEMP3               1501
#define CONFIG_OPTIDLEUPTIME            1502
#define CONFIG_OPTIDLEMSG               1503
#define IDB_BITMAP2                     5001
#define IDD_CONFIGPAGE0                 6000
#define IDD_CONFIGPAGE1                 6001
#define IDD_CONFIGPAGE2                 6002
#define IDD_CONFIGPAGE3                 6003
#define IDD_CONFIGPAGE4                 6004
#define IDD_CONFIGPAGE5                 6005
#define CONFIG_BRSHHATCH0               8000
#define CONFIG_BRSHHATCH1               8001
#define CONFIG_BRSHHATCH2               8002
#define CONFIG_BRSHHATCH3               8003
#define CONFIG_BRSHHATCH4               8004
#define CONFIG_BRSHHATCH5               8005
#define CONFIG_BRSHHATCH6               8006
#define ID_BOT_CONNECT                  40001
#define ID_BOT_DISCONNECT               40002
#define ID_BOT_UNLOADBOT                40003

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        126
#define _APS_NEXT_COMMAND_VALUE         40004
#define _APS_NEXT_CONTROL_VALUE         1168
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif

